import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en" style={{ height: '100vh', width: '100vw', margin: 0, padding: 0 }}>
        <body style={{ height: '100%', margin: 0, padding: 0, }}>
          {children}
        </body>
      </html>
    </>
  )
}
