import { openai } from '@ai-sdk/openai';
import { generateText } from 'ai';



export async function POST(request: Request) {
    // Get s from the request body
    const { s } = await request.json();
    console.log(s);
    // Pass s to openai
    const { text } = await generateText({
        model: openai('gpt-3.5-turbo'),
        prompt: s,
    });
    return new Response(text);
    // Parse openai intent, categories and keywords response
    // Consult mongodb to find products for categories and keywords
    // Build a response object
    // A response generated by the openai responding for the intent
    // A set of cards for the obtained products with a brief description generated by openai
}